version: '3.8'

services:
  my-spring-boot-app:
    image: foxxx614/virt3_t2
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: postgres
      DB_USERNAME: fox
      DB_PASSWORD: fox
      APP_PORT: 8080

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: fox
      POSTGRES_PASSWORD: fox
    ports:
      - "5421:5432"
